# Generated by Django 5.2.6 on 2025-09-04 14:06

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Produto"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição Curta"
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço (MZN)"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Original",
                    ),
                ),
                (
                    "is_on_sale",
                    models.BooleanField(default=False, verbose_name="Em Promoção"),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Nível Mínimo de Estoque"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_upload_path,
                        verbose_name="Imagem Principal",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_upload_path,
                        verbose_name="Imagem 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_upload_path,
                        verbose_name="Imagem 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_upload_path,
                        verbose_name="Imagem 4",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Especificações Técnicas"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Título"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Descrição"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("out_of_stock", "Fora de Estoque"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Produto em Destaque"
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="Mais Vendido"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Comprimento (cm)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Largura (cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Altura (cm)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vendas"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"],
                        name="products_pr_status_142af0_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="products_pr_is_feat_a5d7cd_idx"
                    ),
                    models.Index(
                        fields=["is_bestseller"], name="products_pr_is_best_2e3920_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="products_pr_created_52f0d7_idx"
                    ),
                ],
            },
        ),
    ]
