# Generated by Django 4.2.7 on 2025-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome da Cor"
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        help_text="Ex: #FF0000", max_length=7, verbose_name="Código Hex"
                    ),
                ),
                (
                    "rgb_code",
                    models.CharField(
                        blank=True,
                        help_text="Ex: rgb(255,0,0)",
                        max_length=20,
                        verbose_name="Código RGB",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cor",
                "verbose_name_plural": "Cores",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="SKU"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, to="products.color", verbose_name="Cores Disponíveis"
            ),
        ),
    ]
