# Generated by Django 4.2.7 on 2025-09-05 21:30

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_color_alter_product_sku_product_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.product_image_upload_path,
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texto Alternativo"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Imagem Principal"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Produto",
                "verbose_name_plural": "Imagens do Produto",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_main"],
                        name="products_pr_product_a6a200_idx",
                    ),
                    models.Index(
                        fields=["product", "order"],
                        name="products_pr_product_e55bb9_idx",
                    ),
                ],
            },
        ),
    ]
