# Generated by Django 4.2.7 on 2025-09-13 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_readd_category_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
    ]
