# Generated by Django 4.2.7 on 2025-09-23 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Moderação"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Moderado por",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_notes",
            field=models.TextField(blank=True, verbose_name="Notas da Moderação"),
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
