# Generated by Django 4.2.7 on 2025-10-19 18:44

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_review_moderated_at_review_moderated_by_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE products_review "
                        "ADD COLUMN IF NOT EXISTS admin_seen boolean NOT NULL DEFAULT false;"
                        "CREATE INDEX IF NOT EXISTS products_review_admin_seen_idx ON products_review (admin_seen);"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS products_review_admin_seen_idx;"
                        "ALTER TABLE products_review DROP COLUMN IF EXISTS admin_seen;"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="review",
                    name="admin_seen",
                    field=models.BooleanField(
                        db_index=True, default=False, verbose_name="Visto pelo Admin"
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.review_image_upload_path,
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.review",
                        verbose_name="Avaliação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Avaliação",
                "verbose_name_plural": "Imagens das Avaliações",
                "ordering": ["id"],
            },
        ),
    ]
