# Generated by Django 4.2.7 on 2025-10-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0011_remove_review_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Votos úteis"
            ),
        ),
        # Ensure unique_together is removed (allow multiple reviews per user/product)
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="ReviewHelpfulVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Votado em"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_votes",
                        to="products.review",
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_helpful_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto Útil da Avaliação",
                "verbose_name_plural": "Votos Úteis das Avaliações",
                "indexes": [
                    models.Index(
                        fields=["review", "user"], name="products_re_review__327244_idx"
                    )
                ],
                "unique_together": {("review", "user")},
            },
        ),
    ]
