# Generated by Django 4.2.7 on 2025-10-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0009_review_moderated_at_review_moderated_by_and_more"),
        ("cart", "0003_extend_order_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("processing", "Processando"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                            ("paid", "Pago"),
                            ("failed", "Falhou"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("processing", "Processando"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                            ("paid", "Pago"),
                            ("failed", "Falhou"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Históricos de Status",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("sale", "Venda"),
                            ("return", "Devolução"),
                            ("restock", "Reposição"),
                            ("adjustment", "Ajuste"),
                            ("damage", "Dano/Perda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_stock", models.IntegerField()),
                ("new_stock", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observações Internas"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Entrega Padrão"),
                    ("express", "Entrega Expressa"),
                    ("pickup", "Retirada na Loja"),
                    ("same_day", "Entrega no Mesmo Dia"),
                ],
                default="standard",
                max_length=50,
                verbose_name="Método de Entrega",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmado"),
                    ("processing", "Processando"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                    ("refunded", "Reembolsado"),
                    ("paid", "Pago"),
                    ("failed", "Falhou"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="cart_order_status_8d147d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="cart_order_user_id_fd75e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="cart_order_order_n_bd9406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tracking_number"], name="cart_order_trackin_06d5aa_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.order",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="cart.order",
            ),
        ),
    ]
