# Generated by Django 4.2.7 on 2025-10-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0002_promotion_allowed_roles"),
        ("cart", "0004_orderstatushistory_stockmovement_alter_order_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional site-wide promotion applied to this cart",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotions.promotion",
            ),
        ),
    ]
