# Generated by Django 4.2.7 on 2025-10-11 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_ensure_applied_promotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="applied_promotion",
        ),
    ]
