# Generated by Django 4.2.7 on 2025-10-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_remove_cart_applied_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_seen",
            field=models.BooleanField(default=False, verbose_name="Visto pelo Admin"),
        ),
    ]
