# Generated by Django 4.2.7 on 2025-10-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_order_admin_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="cart.cart",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="request_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="cart.order",
            ),
        ),
    ]
