# Generated by Django 4.2.7 on 2025-10-13 07:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_review_moderated_at_review_moderated_by_and_more"),
        ("cart", "0010_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="line_total",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("delivery_time", models.CharField(blank=True, max_length=100)),
                ("regions", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color_name", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
    ]
