# Generated by Django 4.2.7 on 2025-10-13 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_alter_orderitem_options_remove_orderitem_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Método de Envio",
                "verbose_name_plural": "Métodos de Envio",
            },
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="color",
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="color_name",
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="line_total",
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="unit_price",
        ),
    ]
