# Generated by Django 4.2.7 on 2025-10-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_alter_shippingmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carthistory",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Criado"),
                    ("item_added", "Item Adicionado"),
                    ("item_removed", "Item Removido"),
                    ("item_updated", "Item Atualizado"),
                    ("coupon_applied", "Cupom Aplicado"),
                    ("coupon_removed", "Cupom Removido"),
                    ("abandoned", "Abandonado"),
                    ("recovery_sent", "Email de Recuperação Enviado"),
                    ("converted", "Convertido"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("emola", "e-mola")], max_length=30
            ),
        ),
    ]
