# Generated by Django 4.2.7 on 2025-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0013_alter_carthistory_event_alter_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carthistory",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Criado"),
                    ("item_added", "Item Adicionado"),
                    ("item_removed", "Item Removido"),
                    ("item_updated", "Item Atualizado"),
                    ("coupon_applied", "Cupom Aplicado"),
                    ("coupon_removed", "Cupom Removido"),
                    ("abandoned", "Abandonado"),
                    ("recovery_sent", "Email de Recuperação Enviado"),
                    ("converted", "Convertido"),
                ],
                max_length=20,
            ),
        ),
    ]
