# Generated by Django 4.2.7 on 2025-10-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0014_alter_carthistory_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="last_polled_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time payment status was checked", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="poll_count",
            field=models.IntegerField(
                default=0, help_text="Number of times payment status was polled"
            ),
        ),
        migrations.AlterField(
            model_name="carthistory",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Criado"),
                    ("item_added", "Item Adicionado"),
                    ("item_removed", "Item Removido"),
                    ("item_updated", "Item Atualizado"),
                    ("coupon_applied", "Cupom Aplicado"),
                    ("coupon_removed", "Cupom Removido"),
                    ("abandoned", "Abandonado"),
                    ("recovery_sent", "Email de Recuperação Enviado"),
                    ("converted", "Convertido"),
                ],
                max_length=50,
            ),
        ),
    ]
