# Generated by Django 4.2.7 on 2025-10-18 16:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_review_moderated_at_review_moderated_by_and_more"),
        ("cart", "0015_payment_last_polled_at_payment_poll_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color_hex",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="dimensions",
            field=models.CharField(
                blank=True, help_text="Dimensões (LxWxH)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso em kg",
                max_digits=10,
                null=True,
            ),
        ),
    ]
