# Generated by Django 4.2.7 on 2025-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_role_externalauthuser"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, only users with these roles can use the promotion",
                related_name="promotions",
                to="customers.role",
            ),
        ),
    ]
