# Generated by Django 4.2.7 on 2025-10-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_role_externalauthuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Casa, Trabalho, Apartamento",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome do destinatário", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(help_text="Telefone de contato", max_length=30),
                ),
                (
                    "address",
                    models.CharField(help_text="Endereço completo", max_length=255),
                ),
                ("city", models.CharField(help_text="Cidade", max_length=100)),
                ("province", models.CharField(help_text="Província", max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Código postal", max_length=20
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Endereço padrão para checkout"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço do Cliente",
                "verbose_name_plural": "Endereços dos Clientes",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
