# Generated by Django 4.2.7 on 2025-10-23
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0003_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='postal_code',
            field=models.CharField(max_length=20, blank=True),
        ),
    ]
